spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_composer
    username: root
    password: root
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY:sk-ws-H.ELDILDH.T5gu.MEQCIGsJS69YI3_nEiK79B7stAT4i5BmSTRYOZJKzw_ZGkzVAiBbkDaUqdZrrTj9DdqmkaKYF9NACMPvMZvGOAWz9gNZaw}
      chat:
        options:
          model: glm-5.2
#      base-url: https://ws-638y1k8k3dlbbm2s.cn-beijing.maas.aliyuncs.com/api/v1